file_size:
  name: File Size
  limit: 10485760
composer:
  name: Composer Validate
  bin: composer
  no_check_all: true
  no_check_publish: true
magento_coding_standard:
  name: Magento Coding Standard
  bin: vendor/squizlabs/php_codesniffer/bin/phpcs
  standard: dev/tests/static/framework/Magento/ruleset.xml
  fixer: vendor/squizlabs/php_codesniffer/bin/phpcbf
bss_coding_standard:
  name: Bss Coding Standard
  bin: var/bss/vendor/squizlabs/php_codesniffer/bin/phpcs
  standard: var/bss/Bss
  fixer: var/bss/vendor/squizlabs/php_codesniffer/bin/phpcbf
phpmd:
  name: PHPMD
  bin: vendor/phpmd/phpmd/src/bin/phpmd
  standard: dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
php7_compatibility:
  name: PHP Compatibility
  bin: vendor/squizlabs/php_codesniffer/bin/phpcs
  standard: PHPCompatibility
  version: 7.2-8.1
phpstan:
  name: PHPStan
  bin: vendor/bin/phpstan
  format: filtered
  standard: dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon
  deprecation: false
phpcpd:
  name: PHP Copy/Paste Detector
  bin: vendor/sebastian/phpcpd/phpcpd
  min_lines: 13
  fuzzy: true
  folder: app/code/
php_cs_fixer:
  name: PHP Coding Standards Fixer
  bin: vendor/friendsofphp/php-cs-fixer/php-cs-fixer
  standard: .php-cs-fixer.dist.php
phpmnd:
  name: PHP Magic Number Detector
  bin: var/bss/vendor/povils/phpmnd/bin/phpmnd
  suffixes: php,phtml
less:
  name: Less
  bin: vendor/phpunit/phpunit/phpunit
  suite: Less Static Code Analysis
  standard: dev/tests/static/phpunit.xml.dist
  blacklist: dev/tests/static/testsuite/Magento/Test/Less/_files/blacklist/
html:
  name: HTML
  bin: vendor/phpunit/phpunit/phpunit
  suite: HTML Static Code Analysis
  standard: dev/tests/static/phpunit.xml.dist
eslint:
  name: ESLint
  bin: eslint
  format: stylish
  standard: vendor/magento/magento-coding-standard/eslint/.eslintrc-magento
  ignore: dev/tests/static/testsuite/Magento/Test/Js/_files/blacklist/magento.txt
